apiVersion: apps/v1
kind: Deployment
metadata:
  name: offres-service
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: offres-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.profil }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
